OPENCLAW_API_URL=${OPENCLAW_URL}
ASTERISK_ARI_USER=${ARI_USERNAME}
ASTERISK_ARI_PASSWORD=${ARI_PASSWORD}
ASTERISK_AMI_USER=${AMI_USERNAME}
ASTERISK_AMI_PASSWORD=${AMI_PASSWORD}
ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
