; AVA AI Voice Agent — Dialplan
; Generated by install-pbx.sh

[ava-outbound]
exten => _+.,1,NoOp(AVA Outbound Call: ${EXTEN})
 same => n,Set(AUDIO_UUID=${SHELL(uuidgen)})
 same => n,AMD()
 same => n,GotoIf($["${AMDSTATUS}" = "MACHINE"]?voicemail)
 same => n,AudioSocket(${AUDIO_UUID},${AI_HOST}:${AUDIOSOCKET_PORT})
 same => n,Hangup()
 same => n(voicemail),Playback(vm-goodbye)
 same => n,Hangup()

[ava-inbound]
exten => s,1,NoOp(AVA Inbound Call)
 same => n,Set(AUDIO_UUID=${SHELL(uuidgen)})
 same => n,AudioSocket(${AUDIO_UUID},${AI_HOST}:${AUDIOSOCKET_PORT})
 same => n,Hangup()

[outbound-sipgate]
exten => _+.,1,Dial(SIP/${EXTEN}@sipgate-trunk)
 same => n,Hangup()
