; Sipgate SIP Trunk for AVA
; Generated by install-pbx.sh

[sipgate-trunk]
type=peer
host=${SIPGATE_HOST}
username=${SIP_AUTH_USER}
secret=${SIP_AUTH_PASS}
fromuser=${SIP_AUTH_USER}
fromdomain=sipgate.de
insecure=invite,port
qualify=yes
nat=force_rport,comedia
dtmfmode=rfc2833
disallow=all
allow=ulaw
allow=alaw
allow=g722
context=ava-inbound
